services:
  home-soc-monitor:
    build: .
    container_name: home-soc-monitor
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: docker

  attacker:
    image: curlimages/curl:8.10.1
    container_name: home-soc-attacker
    profiles:
      - attack
    depends_on:
      - home-soc-monitor
    environment:
      API_URL: http://home-soc-monitor:8080
      SOURCE_IP: 192.168.0.14
      SOURCE_MAC: AA:BB:CC:05
      VENDOR: IoT Camera
    volumes:
      - ./scripts:/scripts:ro
    entrypoint: ["sh", "/scripts/attacker-exfil.sh"]
